name: Hello World Action
author: author_demo
description: アクションファイルのパス参照
inputs:
  # 環境変数 INPUT_NUMOCTOCATS
  numOctocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  # 環境変数 INPUT_OCTOCATEYECOLOR
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true
    deprecationMessage: '非推奨の警告メッセージです'
outputs:
  random-number: # 出力のid
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
  sum-s:
    description: "Random number"

